"""Shared-secret gate for the demo's write paths.

The public demo has no user accounts. Anything that mutates state (lead
status transitions) and anything we want to treat as "the operator did
this" (trusted orb runs whose prompts may be shown verbatim on the
Dashboard feed) is gated on a single secret sent as `X-Write-Token`.

The token is generated by Terraform, stored in Key Vault and injected as
DEMO_WRITE_TOKEN. The operator unlocks a browser session by visiting the
site once with `?write_token=<value>`; the frontend keeps it in
sessionStorage and adds the header to every API call.

Fail closed: if no token is configured, writes are refused everywhere.
Local dev sets DEMO_WRITE_TOKEN in .env (see .env.example).
"""

from __future__ import annotations

import hmac

from fastapi import HTTPException, Request

from src.settings import settings

HEADER = "x-write-token"


def has_write_token(request: Request) -> bool:
    """True when the request carries the configured write token."""
    configured = settings.demo_write_token
    supplied = request.headers.get(HEADER, "")
    if not configured or not supplied:
        return False
    return hmac.compare_digest(configured.encode("utf-8"), supplied.encode("utf-8"))


async def require_write_token(request: Request) -> None:
    """FastAPI dependency for mutating endpoints."""
    if not settings.demo_write_token:
        raise HTTPException(
            status_code=403,
            detail="Writes are disabled on this deployment (no DEMO_WRITE_TOKEN configured).",
        )
    if not has_write_token(request):
        raise HTTPException(
            status_code=401,
            detail="This action requires the demo write token (X-Write-Token header).",
        )
